VERSION=`cat ./VERSION | awk NF`

all: clean update_version_file linux macos windows

clean:
	rm -f build/*

update_version_file:
	echo "// File autogenerated from VERSION, do not change manually!\npackage main\n\nconst AppVersion = \"${VERSION}\"" > src/version.go

linux: linux_amd64 linux_arm64 linux_arm

macos: macos_amd64 macos_arm64

windows: windows_amd64 windows_arm64

linux_amd64:
	env GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o build/go-hole_linux_amd64_${VERSION} src/*.go

linux_arm64:
	env GOOS=linux GOARCH=arm64 go build -ldflags="-w -s" -o build/go-hole_linux_arm64_${VERSION} src/*.go

linux_arm:
	env GOOS=linux GOARCH=arm go build -ldflags="-w -s" -o build/go-hole_linux_arm_${VERSION} src/*.go

macos_amd64:
	env GOOS=darwin GOARCH=amd64 go build -ldflags="-w -s" -o build/go-hole_macos_amd64_${VERSION} src/*.go

macos_arm64:
	env GOOS=darwin GOARCH=arm64 go build -ldflags="-w -s" -o build/go-hole_macos_arm64_${VERSION} src/*.go

windows_amd64:
	env GOOS=windows GOARCH=amd64 go build -ldflags="-w -s" -o build/go-hole_windows_amd64_${VERSION}.exe src/*.go

windows_arm64:
	env GOOS=windows GOARCH=arm64 go build -ldflags="-w -s" -o build/go-hole_windows_arm64_${VERSION}.exe src/*.go